### ISSUE TITLE
界高顺【禁酒】点数异常问题未修复

### ISSUE THREAD

**Issue by Buddha-like-Tall-nut** [diandian157/decadeUI#34]
大佬你好，下载了最新的十周年UI，发现界高顺【禁酒】异常的问题仍未修复。之前的issue已关闭，所以又开了一个，希望能再排查一下。
问题说明：界高顺【禁酒】：所有【酒】点数均视为K。
开启此十周年UI后，拼点时【酒】的点数会恢复为原点数
关闭此十周年UI后，问题消失。

**Comment by mengxinzxz** [comment]
![image](https://github.com/user-attachments/assets/93e28acf-b99a-4ecf-8a79-343a74c7b3b0)
抱歉哈修复没提上去，我的锅

**Comment by mengxinzxz** [comment]
![image](https://github.com/user-attachments/assets/a1c69c6a-ff85-4b42-a198-53f83b7498a1)
被一个作者线下让我提的内容覆盖了，重新提上去了

**Comment by Buddha-like-Tall-nut** [comment]
好的，刚试了下，已经没问题了。谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月21日(星期四) 晚上10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mengxinzxz/decadeUI--mx] 界高顺【禁酒】点数异常问题未修复 (Issue #34)














 
image.png (view on web)
 被一个作者线下让我提的内容覆盖了，重新提上去了
